#!/bin/bash 
mas install 865500966 # feedly
mas install 886106985 # Sunrise Calendar
mas install 417375580 # BetterSnapTool
mas install 823766827 # OneDrive
mas install 497799835 # Xcode
mas install 539883307 # LINE
mas install 1090969894 # Escape
mas install 410628904 # Wunderlist
mas install 451444120 # Memory Clean
mas install 961632517 # Be Focused Pro
mas install 404478020 # OmniOutliner
# http://www.softantenna.com/wp/mac/mas-cli/
